os: linux
dist: xenial
language: cpp

compiler:
  - clang

addons:
    apt:
        sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
            - libopenal-dev
            - libjpeg-dev
            - libudev-dev
            - libxrandr-dev
            - libfreetype6-dev
            - libvorbis-dev
            - libflac-dev
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libxi-dev
            - g++-8
            - cmake
            - cxxtest
            - libtinyxml2-dev
            - libglm-dev
            - liblua5.2-dev

before_install:
  - sudo cp /usr/include/lua5.2/* /usr/include/

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j8

notifications:
  email: false

